---
title: "Teaching Analytics"
author: "ROUX Dorian"
output: html_document
---

```{r}
#Import the Libraries.
library('readr')
library('dplyr')
library("tidyr")
library("RColorBrewer")
library('TraMineR')
library('ggplot2')
```

```{r}
#Import the Dataframe.
prep_Sequences <- read_csv(file ='../Data/Quizzes.csv') #Import the required CSV.
prep_Sequences <- select(prep_Sequences, -c(1)) #Remove the first column that represents the index.
head(prep_Sequences, 10) #Display the ten first rows.
```

```{r}
#Save a a Spread Dataframe.
seq_Spread <- spread(prep_Sequences, Rank, Correct_Difficulty) #Spread the previous Dataframe.
write.csv(seq_Spread,'../Data/Spead_Sequences.csv', row.names = FALSE) #Save the Spread Dataframe into a CSV file
```

```{r}
prep_Sequences_mod2chap1 <- prep_Sequences %>% filter(Departement == "Informatique" & Module_ID == 2 & Chapter_ID == 1)
prep_Sequences_mod2chap1$Quizz_ID <- replace(prep_Sequences_mod2chap1$Quizz_ID, prep_Sequences_mod2chap1$Quizz_ID>=0, prep_Sequences_mod2chap1$Quizz_ID - prep_Sequences_mod2chap1$Quizz_ID[1] + 1)
unique(prep_Sequences_mod2chap1$Module)
prep_Sequences_mod2chap1_DS <- prep_Sequences_mod2chap1 %>% select(Quizz_ID, Year, Chapter_ID, Difficulty_String)
seq_Sequences_mod2chap1_DS <- spread(prep_Sequences_mod2chap1_DS, Quizz_ID, Difficulty_String)
mvad.Sequences_mod2chap1_DS <- seqdef(seq_Sequences_mod2chap1_DS[, -c(1:2)])

seqplot_color = c("#FF0000",   "#000FFF",   "#F4EFD7",   "#FF7878", "#7878FF")
legend_color = c('#FF0000', '#FF7878', '#F4EFD7', '#7878FF', '#000FFF')
legend_order = c('Beaucoup plus Difficile', 'Plus Difficile', 'Meme Difficulté', 'Plus Facile', 'Beaucoup plus Facile')
  
prep_Sequences_mod2chap1_DS
png(file="../Figures/Test.png", heigh = 600, width = 1200)
par(mar=c(6,6,0,2)+0.1, oma=c(0,0,7,0))
layout(matrix(c(1, 1, 2), ncol=3, byrow=TRUE))

seqiplot(mvad.Sequences_mod2chap1_DS, with.legend=FALSE, cpal = seqplot_color, ytlab=seq_Sequences_mod2chap1_DS$Year, ylas=0, cex.lab = 2.5, cex.axis = 2.5, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")

seqlegend(mvad.Sequences_mod2chap1_DS, cpal = legend_color, ltext = legend_order, cex =2.5, position = 'center')

text(1, 0.4, paste("Difficulté Réel par rapport à la Prédiction"), cex = 2.3)


title_Sequences_mod2chap1_DS = paste(
  "Séquences de la Différence entre la Difficulté Prédite et Réel, \n",
  "pour les Quiz du chapitre", paste("«", unique(prep_Sequences_mod2chap1$Chapter), "»,", sep = ""), 
  "du module", paste("«", unique(prep_Sequences_mod2chap1$Module), "»,", sep = ""),
  "du Département", paste("d'", unique(prep_Sequences_mod2chap1$Departement), sep = ""),
  "de 2015 à 2020"
)


mtext(title_Sequences_mod2chap1_DS, outer=TRUE,  cex=1.5, line=1)

dev.off()
```


```{r}
prep_Sequences_mod1chap1 <- prep_Sequences %>% filter(Departement == "Informatique" & Module_ID == 3 & Chapter_ID == 2)
prep_Sequences_mod1chap1$Quizz_ID <- replace(prep_Sequences_mod1chap1$Quizz_ID, prep_Sequences_mod1chap1$Quizz_ID>=0, prep_Sequences_mod1chap1$Quizz_ID - prep_Sequences_mod1chap1$Quizz_ID[1] + 1)

prep_Sequences_mod1chap2_DS <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Difficulty_String)
seq_Sequences_mod1chap2_DS <- spread(prep_Sequences_mod1chap2_DS, Quizz_ID, Difficulty_String)
mvad.Sequences_mod1chap2_DS <- seqdef(seq_Sequences_mod1chap2_DS[, -c(1:2)])

prep_Sequences_Adapte <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Difficulty)
seq_Sequences_Adapte <- spread(prep_Sequences_Adapte, Quizz_ID, Difficulty)
mvad.Sequences_Adapte <- seqdef(seq_Sequences_Adapte[, -c(1:2)])


col_correct_prediction = c('#B71C1C', '#0D47A1', '#AED581', '#E57373', '#64B5F6')
col_correct_Adapte = c('#FFE0B2', '#FF5722')

png(file="../Figures/Test2.png", heigh = 600, width = 1200)
layout(matrix(c(1, 1, 1, 2, 2, 3, 3, 3, 3, 4), ncol=5, byrow=TRUE))
par(mar=c(5,5,3,5)+0.1, oma=c(0,0,6,0))

seqiplot(mvad.Sequences_mod1chap2_DS, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Sequences_mod1chap2_DS$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.3, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des différences de niveaux de difficulté des quiz entre la prédiction de l'enseignant et la réalité \n pour le chapitre «Instruction de Base» du module «Algorithme et Programmation» de 2015 à 2020",  cex = 1.5, font = 1))

seqlegend(mvad.Sequences_mod1chap2_DS, cpal = col_correct_prediction, cex =1.8, position = 'center')

seqiplot(mvad.Sequences_Adapte, with.legend=FALSE, cpal = col_correct_Adapte, ytlab=seq_Sequences_Adapte$Year, ylas=1, cex.lab = 1.8, cex.axis = 1.3, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences de validation de la difficulté des quiz \n pour le chapitre «Instruction de Base» du module «Algorithme et Programmation» de 2015 à 2020",  cex = 1.5, font = 1))

mtext("Séquences sur les difficultés des Quiz \n pour le chapitre «Instruction de Base» du module «Algorithme et Programmation» du département d'Informatique de 2015 à 2020", outer=TRUE,  cex=1.5, line=1)

seqlegend(mvad.Sequences_Adapte, cpal = col_correct_Adapte, cex =2, position = 'center')

dev.off()
```
```{r}
prep_Sequences_mod1chap1 <- prep_Sequences %>% filter(Departement == "Informatique" & Module_ID == 3 & Chapter_ID == 2)
prep_Sequences_mod1chap1$Quizz_ID <- replace(prep_Sequences_mod1chap1$Quizz_ID, prep_Sequences_mod1chap1$Quizz_ID>=0, prep_Sequences_mod1chap1$Quizz_ID - prep_Sequences_mod1chap1$Quizz_ID[1] + 1)

prep_Sequences_mod1chap2_DS <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Difficulty_String)
seq_Sequences_mod1chap2_DS <- spread(prep_Sequences_mod1chap2_DS, Quizz_ID, Difficulty_String)
mvad.Sequences_mod1chap2_DS <- seqdef(seq_Sequences_mod1chap2_DS[, -c(1:2)])

prep_Sequences_Correct <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Correct_Difficulty)
seq_Sequences_Correct <- spread(prep_Sequences_Correct, Quizz_ID, Correct_Difficulty)
mvad.Sequences_Correct <- seqdef(seq_Sequences_Correct[, -c(1:2)])

prep_Sequences_Prediction <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Predict_Difficulty)
seq_Sequences_Prediction <- spread(prep_Sequences_Prediction, Quizz_ID, Predict_Difficulty)
mvad.Sequences_Prediction <- seqdef(seq_Sequences_Prediction[, -c(1:2)])

col_correct_prediction = c('red', 'blue', 'green')
col_diff_diffic = c('#B71C1C', '#0D47A1', '#AED581', '#E57373', '#64B5F6')

png(file="../Figures/Test222.png", heigh = 600, width = 1200)
layout(matrix(c(1, 1, 2, 2, 3), ncol=5, byrow=TRUE))
par(mar=c(5,5,3,5)+0.1, oma=c(0,0,6,0))

seqiplot(mvad.Sequences_Prediction, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Sequences_Prediction$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.3, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des niveaux de difficulté des quiz prédit par l'enseignant \n pour le chapitre «Instruction de Base» de 2015 à 2020",  cex = 1.5, font = 1))

seqiplot(mvad.Sequences_Correct, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Sequences_Correct$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.3, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des niveaux de difficulté des quiz correct \n pour le chapitre «Instruction de Base» de 2015 à 2020",  cex = 1.5, font = 1))

seqlegend(mvad.Sequences_Correct, cpal = col_correct_prediction, cex =1.8, position = 'center')

mtext("Séquences sur les difficultés des Quiz Prédit et Correct \n pour le chapitre «Instruction de Base» du module «Algorithme et Programmation» du département d'Informatique de 2015 à 2020", outer=TRUE,  cex=1.5, line=1)

dev.off()
```

```{r}
prep_Sequences_mod1chap1 <- prep_Sequences %>% filter(Departement == "Informatique" & Module_ID == 3 & Chapter_ID == 2)
prep_Sequences_mod1chap1$Quizz_ID <- replace(prep_Sequences_mod1chap1$Quizz_ID, prep_Sequences_mod1chap1$Quizz_ID>=0, prep_Sequences_mod1chap1$Quizz_ID - prep_Sequences_mod1chap1$Quizz_ID[1] + 1)

prep_Sequences_mod1chap2_DS <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Difficulty_String)
seq_Sequences_mod1chap2_DS <- spread(prep_Sequences_mod1chap2_DS, Quizz_ID, Difficulty_String)
mvad.Sequences_mod1chap2_DS <- seqdef(seq_Sequences_mod1chap2_DS[, -c(1:2)])

prep_Sequences_Correct <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Correct_Difficulty)
seq_Sequences_Correct <- spread(prep_Sequences_Correct, Quizz_ID, Correct_Difficulty)
mvad.Sequences_Correct <- seqdef(seq_Sequences_Correct[, -c(1:2)])

prep_Sequences_Prediction <- prep_Sequences_mod1chap1 %>% select(Quizz_ID, Year, Chapter_ID, Predict_Difficulty)
seq_Sequences_Prediction <- spread(prep_Sequences_Prediction, Quizz_ID, Predict_Difficulty)
mvad.Sequences_Prediction <- seqdef(seq_Sequences_Prediction[, -c(1:2)])

col_correct_prediction = c('red', 'blue', 'green')
col_diff_diffic = c('#B71C1C', '#0D47A1', '#AED581', '#E57373', '#64B5F6')

png(file="../Figures/Test22.png", heigh = 600, width = 1200)
layout(matrix(c(1, 1, 2, 2, 3, 4, 4, 4, 5, 5), ncol=5, byrow=TRUE))
par(mar=c(5,5,3,5)+0.1, oma=c(0,0,6,0))

seqiplot(mvad.Sequences_Prediction, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Sequences_Prediction$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.3, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des niveaux de difficulté des quiz prédit par l'enseignant \n pour le chapitre «Instruction de Base» de 2015 à 2020",  cex = 1.5, font = 1))

seqiplot(mvad.Sequences_Correct, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Sequences_Correct$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.3, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des niveaux de difficulté des quiz correct \n pour le chapitre «Instruction de Base» de 2015 à 2020",  cex = 1.5, font = 1))

seqlegend(mvad.Sequences_Correct, cpal = col_correct_prediction, cex =1.8, position = 'center')

seqiplot(mvad.Sequences_mod1chap2_DS, with.legend=FALSE, cpal = col_diff_diffic, ytlab=seq_Sequences_mod1chap2_DS$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.3, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des différences de niveaux de difficulté des quiz entre la prédiction de l'enseignant et la réalité \n pour le chapitre «Instruction de Base» du module «Algorithme et Programmation» de 2015 à 2020",  cex = 1.5, font = 1))

seqlegend(mvad.Sequences_mod1chap2_DS, cpal = col_diff_diffic, cex =1.8, position = 'center')

mtext("Séquences sur les difficultés des Quiz Prédit et Correct ainsi que leur différence \n pour le chapitre «Instruction de Base» du module «Algorithme et Programmation» du département d'Informatique de 2015 à 2020", outer=TRUE,  cex=1.5, line=1)

dev.off()
```


```{r}
prep_Sequences_8 <- prep_Sequences %>% filter(Departement == 'Informatique', Chapter_ID == 8)

prep_Sequences_8_Correct <- prep_Sequences_8 %>% select(Quizz_ID, Year, Chapter_ID, Correct_Difficulty)
seq_Spread_8_Correct <- spread(prep_Sequences_8_Correct, Quizz_ID, Correct_Difficulty)
mvad.Chapt8_Correct <- seqdef(seq_Spread_8_Correct[, -c(1:2)])

prep_Sequences_8_Prediction <- prep_Sequences_8 %>% select(Quizz_ID, Year, Chapter_ID, Predict_Difficulty)
seq_Spread_8_Prediction <- spread(prep_Sequences_8_Prediction, Quizz_ID, Predict_Difficulty)
mvad.Chapt8_Prediction <- seqdef(seq_Spread_8_Prediction[, -c(1:2)])

col_correct_prediction = c('#0BFF00', '#E2ABAB', '#ABCBE2', '#FF0000', '#0000FF')

png(file="../Figures/SeqCorrectPredict_Chap8_Informatique.png", heigh = 600, width = 1200)
layout(matrix(c(1, 1, 3, 3, 2), ncol=5, byrow=TRUE))
par(mar=c(5,5,3,5)+0.1, oma=c(0,0,5,0))

seqiplot(mvad.Chapt8_Prediction, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Spread_8_Prediction$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.5, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = '')
title(main=list("Séquences des niveaux de difficulté des quiz prédit par l'enseignant \n pour le chapitre «8» d'Informatique de 2015 à 2020",  cex = 1.5, font = 1))

seqlegend(mvad.Chapt8_Correct, cpal = col_correct, cex =2, position = 'center')

seqiplot(mvad.Chapt8_Correct, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Spread_8_Correct$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.5, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des niveaux de difficulté des quiz correct \n pour le chapitre «8» d'Informatique de 2015 à 2020",  cex = 1.5, font = 1))
mtext("Séquences du niveau de difficulté prédit et réel de chaque Quiz pour le chapitre «8» d'Informatique de 2015 à 2020", outer=TRUE,  cex=1.5, line=1)

dev.off()
```

```{r}
prep_Sequences_13 <- prep_Sequences %>% filter(Departement == 'Mathematique', Chapter_ID == 13)

prep_Sequences_13$Correct_Difficulty[prep_Sequences_13$Correct_Difficulty == 'Trop Facile'] <- 'Trop Facile - Réussite : 85% à 100%' 
prep_Sequences_13$Correct_Difficulty[prep_Sequences_13$Correct_Difficulty == 'Facile'] <- 'Facile - Réussite : 75 à 85%' 
prep_Sequences_13$Correct_Difficulty[prep_Sequences_13$Correct_Difficulty == 'Adapte'] <- 'Adapte - Réussite : 60 à 75%' 
prep_Sequences_13$Correct_Difficulty[prep_Sequences_13$Correct_Difficulty == 'Difficile'] <- 'Difficile - Réussite : 25 à 60%' 
prep_Sequences_13$Correct_Difficulty[prep_Sequences_13$Correct_Difficulty == 'Trop Difficile'] <- 'Trop Difficile - Réussite : 0 à 25%' 

prep_Sequences_13$Predict_Difficulty[prep_Sequences_13$Predict_Difficulty == 'Trop Facile'] <- 'Trop Facile - Réussite : 85% à 100%' 
prep_Sequences_13$Predict_Difficulty[prep_Sequences_13$Predict_Difficulty == 'Facile'] <- 'Facile - Réussite : 75 à 85%' 
prep_Sequences_13$Predict_Difficulty[prep_Sequences_13$Predict_Difficulty == 'Adapte'] <- 'Adapte - Réussite : 60 à 75%' 
prep_Sequences_13$Predict_Difficulty[prep_Sequences_13$Predict_Difficulty == 'Difficile'] <- 'Difficile - Réussite : 25 à 60%' 
prep_Sequences_13$Predict_Difficulty[prep_Sequences_13$Predict_Difficulty == 'Trop Difficile'] <- 'Trop Difficile - Réussite : 0 à 25%' 


prep_Sequences_13_Type <- prep_Sequences_13 %>% select(Quizz_ID, Year, Chapter_ID, Quizz_Type)
seq_Spread_13_Type <- spread(prep_Sequences_13_Type, Quizz_ID, Quizz_Type)
mvad.Chapt13_Type <- seqdef(seq_Spread_13_Type[, -c(1:2)])

prep_Sequences_13_Correct <- prep_Sequences_13 %>% select(Quizz_ID, Year, Chapter_ID, Correct_Difficulty)
seq_Spread_13_Correct <- spread(prep_Sequences_13_Correct, Quizz_ID, Correct_Difficulty)
mvad.Chapt13_Correct <- seqdef(seq_Spread_13_Correct[, -c(1:2)])

prep_Sequences_13_Prediction <- prep_Sequences_13 %>% select(Quizz_ID, Year, Chapter_ID, Predict_Difficulty)
seq_Spread_13_Prediction <- spread(prep_Sequences_13_Prediction, Quizz_ID, Predict_Difficulty)
mvad.Chapt13_Prediction <- seqdef(seq_Spread_13_Prediction[, -c(1:2)])

col_correct_prediction = c('#0BFF00', '#E2ABAB', '#ABCBE2', '#FF0000', '#0000FF')
col_type = c('#E5A5A5', '#BFE5A5', '#A5C3E5')

png(file="../Figures/SeqTypeCorrectPredict_Chap13_InformatiqueBIS.png", heigh = 600, width = 1200)
layout(matrix(c(1,1,1,1,1,1,2,2,3,3,3,4,4,4,5,5), ncol=8, byrow=TRUE))
par(mar=c(5,5,3,5)+0.1, oma=c(0,0,5,0))

seqiplot(mvad.Chapt13_Type, with.legend=FALSE, cpal = col_type, ytlab=seq_Spread_13_Type$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.5, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = '')
title(main=list("Séquences des type de chaque quiz \n pour le chapitre «13» d'Informatique de 2015 à 2020",  cex = 1.5, font = 1))

seqlegend(mvad.Chapt13_Type, cpal = col_type, cex =2, position = 'center')

seqiplot(mvad.Chapt13_Prediction, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Spread_13_Prediction$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.5, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = '')
title(main=list("Séquences des niveaux de difficulté des quiz prédit par l'enseignant \n pour le chapitre «13» d'Informatique de 2015 à 2020",  cex = 1.5, font = 1))

seqiplot(mvad.Chapt13_Correct, with.legend=FALSE, cpal = col_correct_prediction, ytlab=seq_Spread_13_Correct$Year, ylas=0, cex.lab = 1.8, cex.axis = 1.5, space = 0.15, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique")
title(main=list("Séquences des niveaux de difficulté des quiz correct \n pour le chapitre «13» d'Informatique de 2015 à 2020",  cex = 1.5, font = 1))
mtext("Séquences du niveau de difficulté prédit et réel de chaque Quiz pour le chapitre «13» d'Informatique de 2015 à 2020", outer=TRUE,  cex=1.5, line=1)

seqlegend(mvad.Chapt13_Correct, cpal = col_correct, cex = 1.4, position = 'center')


dev.off()
```


```{r}
#Filter the Sequence Data

prep_Sequences_15 <- prep_Sequences %>% filter(Departement == 'Informatique', Chapter_ID == 15)

prep_Sequences_15_Type <- prep_Sequences_15 %>% select(Quizz_ID, Year, Chapter_ID, Quizz_Type)
seq_Spread_15_Type <- spread(prep_Sequences_15_Type, Quizz_ID, Quizz_Type)
mvad.Chapt15_Type <- seqdef(seq_Spread_15_Type[, -c(1:2)])

prep_Sequences_15_Prediction <- prep_Sequences_15 %>% select(Quizz_ID, Year, Chapter_ID, Predict_Difficulty)
seq_Spread_15_Prediction <- spread(prep_Sequences_15_Prediction, Quizz_ID, Predict_Difficulty)
mvad.Chapt15_Prediction <- seqdef(seq_Spread_15_Prediction[, -c(1:2)])

prep_Sequences_15_Correct <- prep_Sequences_15 %>% select(Quizz_ID, Year, Chapter_ID, Correct_Difficulty)
seq_Spread_15_Correct <- spread(prep_Sequences_15_Correct, Quizz_ID, Correct_Difficulty)
mvad.Chapt15_Correct <- seqdef(seq_Spread_15_Correct[, -c(1:2)])

#Build the Sequences Plot and Save them.

png(file="../Figures/Test.png", heigh = 600, width = 1200)
par(mfrow=c(2,3),mar=c(5,5,2,5)+0.1, oma=c(0,0,5,0))
col_type = c('#E5A5A5', '#BFE5A5', '#A5C3E5')
col_pred = c('#FF0000', '#0000FF', '#00FF00', '#FFED00')
col_correct = c('#FF0000', '#C100FF', '#0000FF', '#00FF00', '#FFED00')

seqiplot(mvad.Chapt15_Prediction, with.legend=FALSE, cpal = col_pred, ytlab=seq_Spread_15_Prediction$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, cex.legend=1.2, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = 'Predicted')

seqiplot(mvad.Chapt15_Correct, with.legend=FALSE, cpal = col_correct, ytlab=seq_Spread_15_Correct$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, cex.legend=1.2, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = 'Correct')

seqlegend(mvad.Chapt15_Correct, cpal = col_correct, cex = 1.8, position = 'center')

seqiplot(mvad.Chapt15_Type, with.legend=FALSE, cpal = col_type, ytlab=seq_Spread_15_Type$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, cex.legend=1.2, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = 'Type')

seqlegend(mvad.Chapt15_Type, cpal = col_type, cex = 1.8, position = 'center')

mtext("Séquences Pédagogiques", outer=TRUE,  cex=1.5, line=1)

dev.off()
```
