---
title: "Teaching Analytics"
author: "ROUX Dorian"
output: html_document
---

```{r}
#Import libraries
library('readr')
library('dplyr')
library('TraMineR')
library("tidyr")
library("RColorBrewer")
```

```{r}
sequences <- read_csv(file ='../Data/Prepared_Sequences.csv')
sequences <- select(sequences, -'X1')
head(sequences)
```

```{r}
hist(sequences$Ressources_Amount)
```




```{r}
sequences_Basic <- select(sequences, -'Ressources_Type_Advanced')
seq_dbt <- spread(sequences_Basic, Ressources_Rank,Ressources_Type_Basic)
seq_dbt[seq_dbt == "Vid"] <- "Video"
seq_dbt[is.na(seq_dbt)] <- "Without Ressource"
seq_dbt
```


```{r}
seq_dbt_2016 <- seq_dbt %>% filter(Year == 2016)
seq_dbt_2016

seq_dbt_2016_10frst <- seq_dbt_2016[,-c(2:4)] # Keep the Course_ID
seq_dbt_2016_10frst <- seq_dbt_2016_10frst[] # 10 First_messages
seq_dbt_2016_10frst[is.na(seq_dbt_2016_10frst)] <- 'Empty'

seq_dbt_2016_10frst_cl <- seq_dbt_2016_10frst %>% arrange(Course_ID)

mvad.seq <- seqdef(seq_dbt_2016_10frst_cl[, -c(1:2)])
head(mvad.seq, 10)

seqiplot(mvad.seq, border = NA, withlegend = "right", tlim = 1:20, space=0.1)
```

```{r}
seq_dbt_2017 <- seq_dbt %>% filter(Year == 2017)
seq_dbt_2017

seq_dbt_2017_10frst <- seq_dbt_2017[,-c(2:4)] # Keep the Course_ID
seq_dbt_2017_10frst <- seq_dbt_2017_10frst[] # 10 First_messages
seq_dbt_2017_10frst[is.na(seq_dbt_2017_10frst)] <- 'Empty'

seq_dbt_2017_10frst_cl <- seq_dbt_2017_10frst %>% arrange(Course_ID)

mvad.seq <- seqdef(seq_dbt_2017_10frst_cl[, -c(1:2)])
head(mvad.seq, 10)

seqiplot(mvad.seq, border = NA, withlegend = "right", tlim = 1:20, space=0.1)
```


```{r}
seq_dbt_2018 <- seq_dbt %>% filter(Year == 2018)
seq_dbt_2018

seq_dbt_2018_10frst <- seq_dbt_2018[,-c(2:4)] # Keep the Course_ID
seq_dbt_2018_10frst <- seq_dbt_2018_10frst[] # 10 First_messages
seq_dbt_2018_10frst[is.na(seq_dbt_2018_10frst)] <- 'Empty'

seq_dbt_2018_10frst_cl <- seq_dbt_2018_10frst %>% arrange(Course_ID)

mvad.seq <- seqdef(seq_dbt_2018_10frst_cl[, c(2:10)])
head(mvad.seq, 10)

seqiplot(mvad.seq, border = NA, withlegend = "right", tlim = 1:20, space=0.1)
```

```{r}
seq_dbt_2019 <- seq_dbt %>% filter(Year == 2019)
seq_dbt_2019

seq_dbt_2019_10frst <- seq_dbt_2019[,-c(2:4)] # Keep the Course_ID
seq_dbt_2019_10frst <- seq_dbt_2019_10frst[] # 10 First_messages
seq_dbt_2019_10frst[is.na(seq_dbt_2019_10frst)] <- 'Empty'

seq_dbt_2019_10frst_cl <- seq_dbt_2019_10frst %>% arrange(Course_ID)

mvad.seq <- seqdef(seq_dbt_2019_10frst_cl[, -c(1:2)])
head(mvad.seq, 10)

#seqiplot(mvad.seq, border = NA, withlegend = "right", tlim = 1:20, space=0.1)
seqiplot(mvad.seq, cex.legend=.7, tlim = 1:5)

```


```{r}
#Seqiplot for ID 3

seq_dbt_3 <- seq_dbt %>% filter(Course_ID == 3)
seq_dbt_3
seq_dbt_3_10frst <- seq_dbt_3[,-c(3:4)] # Keep the Course_ID
seq_dbt_3_10frst <- seq_dbt_3_10frst[,-c(19:30)] # 10 First_messages
seq_dbt_3_10frst[is.na(seq_dbt_3_10frst)] <- 'Without Ressource'

#table(is.na(seq_dbt_3_10frst))
#seq_dbt_3_10frst_cl <-drop_na(seq_dbt_3_10frst)
#seq_dbt_3_10frst_cl


mvad.seq <- seqdef(seq_dbt_3_10frst[, -c(1:2)])
head(mvad.seq, 10)

#seqiplot(mvad.seq, border = NA, withlegend = "right", tlim = 1:20, space=0.1)

color = c('blue', 'green', 'red', 'white')
seqiplot(mvad.seq, withlegend='right', ytlab=seq_dbt_3$Year, cpal = color, ylas=1, cex.legend=0.7, ncol=1, ylab = "Years", xlab = "Ressources", title='Sequence of the course identified as N°3 over the years')

```

```{r}
seq_dbt_3_10frst$Year
```

