---
title: "Teaching Analytics"
author: "ROUX Dorian"
output: html_document
---

```{r}
#Import libraries
library('readr')
library('dplyr')
library('TraMineR')
library("tidyr")
```

```{r}
sequences <- read_csv(file ='Data/Prepared_Sequences.csv')
sequences <- select(sequences, -'X1')
head(sequences)
```

```{r}
sequences_Basic <- select(sequences, -'Ressources_Type_Advanced')
seq_dbt <- spread(sequences_Basic, Ressources_Rank,Ressources_Type_Basic)
seq_dbt
```


```{r}
seq_dbt_2016 <- seq_dbt %>% filter(Year == 2016)
seq_dbt_2016

seq_dbt_2016_10frst <- seq_dbt_2016[,-c(2:4)] # Keep the Course_ID
seq_dbt_2016_10frst <- seq_dbt_2016_10frst[,-c(12:31)] # 10 First_messages

seq_dbt_2016_10frst

table(is.na(seq_dbt_2016_10frst))
seq_dbt_2016_10frst_cl <-drop_na(seq_dbt_2016_10frst)
seq_dbt_2016_10frst_cl
```

```{r}
mvad.seq <- seqdef(seq_dbt_2016_10frst_cl[, c(2:10)])
head(mvad.seq, 10)
```

```{r}
seqiplot(mvad.seq, border = NA, withlegend = "right", tlim = 1:20, space=0.1)
```

```{r}
#Seqiplot for ID 3
seq_dbt_3 <- seq_dbt %>% filter(Course_ID == 3)

seq_dbt_3_10frst <- seq_dbt_3[,-c(3:4)] # Keep the Course_ID
seq_dbt_3_10frst <- seq_dbt_3_10frst[,-c(12:32)] # 10 First_messages

table(is.na(seq_dbt_3_10frst))
seq_dbt_3_10frst_cl <-drop_na(seq_dbt_3_10frst)

seq_dbt_3_10frst_cl


mvad.seq <- seqdef(seq_dbt_3_10frst_cl[, c(3:10)])
head(mvad.seq, 10)

seqiplot(mvad.seq, border = NA, withlegend = "right", tlim = 1:20, space=0.1)

```

