---
title: "Teaching Analytics"
author: "ROUX Dorian"
output: html_document
---

```{r}
#Import the Libraries.
library('readr')
library('dplyr')
library('TraMineR')
library("tidyr")
library("RColorBrewer")
library('ggtern')
library('ggplot2')
library("gridExtra")

```

```{r}
#Import the Dataframe.
prep_Sequences <- read_csv(file ='../Data/QuizzesBis.csv') #Import the required CSV.
prep_Sequences <- select(prep_Sequences, -c(1)) #Remove the first column that represents the index.
head(prep_Sequences, 10) #Display the ten first rows.
```

```{r}
#Save a a Spread Dataframe.
seq_Spread <- spread(prep_Sequences, Rank, Correct_Difficulty) #Spread the previous Dataframe.
write.csv(seq_Spread,'../Data/Spead_Sequences.csv', row.names = FALSE) #Save the Spread Dataframe into a CSV file
```



```{r}
#Filter the Sequence Data

prep_Sequences_15 <- prep_Sequences %>% filter(Departement == 'Informatique', Chapter_ID == 15)

prep_Sequences_15_Type <- prep_Sequences_15 %>% select(Quizz_ID, Year, Chapter_ID, Quizz_Type)
seq_Spread_15_Type <- spread(prep_Sequences_15_Type, Quizz_ID, Quizz_Type)
mvad.Chapt15_Type <- seqdef(seq_Spread_15_Type[, -c(1:2)])

prep_Sequences_15_Prediction <- prep_Sequences_15 %>% select(Quizz_ID, Year, Chapter_ID, Predict_Difficulty)
seq_Spread_15_Prediction <- spread(prep_Sequences_15_Prediction, Quizz_ID, Predict_Difficulty)
mvad.Chapt15_Prediction <- seqdef(seq_Spread_15_Prediction[, -c(1:2)])

prep_Sequences_15_Correct <- prep_Sequences_15 %>% select(Quizz_ID, Year, Chapter_ID, Correct_Difficulty)
seq_Spread_15_Correct <- spread(prep_Sequences_15_Correct, Quizz_ID, Correct_Difficulty)
mvad.Chapt15_Correct <- seqdef(seq_Spread_15_Correct[, -c(1:2)])

#Build the Sequences Plot and Save them.

png(file="../Figures/Test.png", heigh = 600, width = 1200)
par(mfrow=c(2,3),mar=c(5,5,2,5)+0.1, oma=c(0,0,5,0))
layout(matrix(c(4, 1, 5, 2, 0, 3), ncol = 3))
col_type = c('#E5A5A5', '#BFE5A5', '#A5C3E5')
col_pred = c('#FF0000', '#0000FF', '#00FF00', '#FFED00')
col_correct = c('#FF0000', '#C100FF', '#0000FF', '#00FF00', '#FFED00')

seqiplot(mvad.Chapt15_Prediction, with.legend=FALSE, cpal = col_pred, ytlab=seq_Spread_15_Prediction$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, cex.legend=1.2, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = 'Predicted')

seqiplot(mvad.Chapt15_Correct, with.legend=FALSE, cpal = col_correct, ytlab=seq_Spread_15_Correct$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, cex.legend=1.2, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = 'Correct')

seqlegend(mvad.Chapt15_Correct, cpal = col_correct, cex = 1.8, position = 'center')

seqiplot(mvad.Chapt15_Type, with.legend=FALSE, cpal = col_type, ytlab=seq_Spread_15_Type$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, cex.legend=1.2, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang et Identification du Quiz dans la Séquence Pédagogique", main = 'Type')

seqlegend(mvad.Chapt15_Type, cpal = col_type, cex = 1.8, position = 'center')

mtext("Séquences Pédagogiques", outer=TRUE,  cex=1.5, line=1)

dev.off()
```
```{r}
x <- pmin(3, pmax(-3, stats::rnorm(50)))
y <- pmin(3, pmax(-3, stats::rnorm(50)))
xhist <- hist(x, breaks = seq(-3,3,0.5), plot = FALSE)
yhist <- hist(y, breaks = seq(-3,3,0.5), plot = FALSE)
top <- max(c(xhist$counts, yhist$counts))
xrange <- c(-3, 3)
yrange <- c(-3, 3)
nf <- layout(matrix(c(2,0,1,3),2,2,byrow = TRUE), c(3,1), c(1,3), TRUE)
layout.show(nf)

par(mar = c(3,3,1,1))
plot(x, y, xlim = xrange, ylim = yrange, xlab = "", ylab = "")
par(mar = c(0,3,1,1))
barplot(xhist$counts, axes = FALSE, ylim = c(0, top), space = 0)
par(mar = c(3,0,1,1))
barplot(yhist$counts, axes = FALSE, xlim = c(0, top), space = 0, horiz = TRUE)
```

```{r}
#Filter the Sequence Data

seq_Spread_843_848_852 <- Seq %>% filter(Course_ID %in% c(843, 848, 852)) %>% filter(Ressources_Amount >= 10)
unique(seq_Spread_843_848_852['Course_ID'])

seq_Spread_843 <- spread(seq_Spread_843_848_852 %>% filter(Course_ID == 843), Ressources_Rank,Ressources_Type_Basic)
seq_Spread_848 <- spread(seq_Spread_843_848_852 %>% filter(Course_ID == 848), Ressources_Rank,Ressources_Type_Basic)
seq_Spread_852 <- spread(seq_Spread_843_848_852 %>% filter(Course_ID == 852), Ressources_Rank,Ressources_Type_Basic)

mvad.Seq_843 <- seqdef(seq_Spread_843[, -c(1:6)])
mvad.Seq_848 <- seqdef(seq_Spread_848[, -c(1:6)])
mvad.Seq_852 <- seqdef(seq_Spread_852[, -c(1:6)])


#Build the Sequences Plot and Save them.

col_843 = c('#ff4646', '#ff8585', '#ffb396', '#4B7BF5', '#79A9F5', '#C2E2F5')
col_848 = c('#ff4646', '#ff8585', '#ffb396', '#4B7BF5', '#79A9F5', '#C2E2F5')
col_852 = c('#ff8585', '#4B7BF5','#79A9F5', '#C2E2F5')

png(file="../Figures/Sequence_SameTeacher_843_848_852.png", heigh =800, width = 1200)
par(mfrow=c(2,2),mar=c(5,5,2,5)+0.1, oma=c(0,0,5,0))

seqiplot(mvad.Seq_843,with.legend = FALSE, cpal = col_843, ytlab=seq_Spread_843$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang dans la Séquence Pédagogique", main = '')
title(main=list('Séquences Pédagogiques pour le module «843» de Sociologie de 2013 à 2020',  cex = 1.5, font = 1))

seqiplot(mvad.Seq_848,with.legend = FALSE, cpal = col_848, ytlab=seq_Spread_848$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang dans la Séquence Pédagogique", main = '')
title(main=list('Séquences Pédagogiques pour le module «848» de Sociologie de 2013 à 2020',  cex = 1.5, font = 1))

seqiplot(mvad.Seq_852,with.legend = FALSE, cpal = col_852, ytlab=seq_Spread_852$Year, ylas=0, cex.lab = 1.5, cex.axis = 1.1, ncol=1, space = 0.1, ylab = "Année", xlab = "Rang dans la Séquence Pédagogique", main = '')
title(main=list('Séquences Pédagogiques pour le module «852» de Sociologie de 2013 à 2020',  cex = 1.5, font = 1))

seqlegend(mvad.seq_843, cpal = col, cex = 1.8, position = 'center')

mtext("Séquences Pédagogiques pour les modules «843», «848» et «852» de Sociologie enseignés par Mme MOULIN de 2013 à 2020", outer=TRUE,  cex=1.5, line=1)

dev.off()
```
